### ISSUE TITLE
Invalid user id throws `IndexError` when trying to decode

### ISSUE THREAD

**Issue by ollemento** [Pevtrick/Flask-Hashids#2]
### Steps to reproduce

* Create and run app (I used this code based off @Pevtrick's example https://github.com/ollemento/Flask-Hashids#examples)
* Request a user with an invalid id, e.g. 
```sh
curl \
  -H 'Content-Type: application/json' \
  localhost:5000/users/404
```

### Expected response

404 Not found

### Actual response

500 Internal server error

```sh
flask_hashids.py", line 65, in decode
    return self._hashids.decode(value)[0]
IndexError: tuple index out of range
```

**Comment by Pevtrick** [comment]
Thanks for your feedback. I created a fix for the issue. Let me know if this is sufficient for your use case.

**Comment by ollemento** [comment]
@Pevtrick looks great!
