### ISSUE TITLE
Hashids may expose SECRET_KEY

### ISSUE THREAD

**Issue by NoRePercussions** [Pevtrick/Flask-Hashids#5]
Hashids (the current version) [is not cryptographically secure](https://carnage.github.io/2015/08/cryptanalysis-of-hashids). Using `SECRET_KEY` as a salt means that Flask's secret key may be recovered, which is a significant risk.

**Comment by Pevtrick** [comment]
Thanks for pointing this out. There is a new release that fixes the problem based on your PR.
