### ISSUE TITLE
Primary key naming in DB models

### ISSUE THREAD

**Issue by Tes3awy** [Pevtrick/Flask-Hashids#7]
Hi @Pevtrick,

First, I want to thank you for this extension and awesomeness. This extension is a huge life saver.

I have a request from you though. Can you please let the attribute name of the ID be either `id` or `pk`?

According to the following note
https://github.com/Pevtrick/Flask-Hashids/blob/14e6ca2a1d67f188dcd10aa18d763e08b6740a4d/flask_hashids.py#L21-L23

And the statically assigned `__id_attibute__`

https://github.com/Pevtrick/Flask-Hashids/blob/14e6ca2a1d67f188dcd10aa18d763e08b6740a4d/flask_hashids.py#L25

If the primary key column is any other name than `id`, you get an error:

```python
class MyModel(HashidMixin, db.Model):
    __tablename__ = "my_model"
    pk = db.Column(db.Integer, primary_key=True)
    ...
```

```bash
AttributeError: 'MyModel' object has no attribute 'id'
```

You might be wondering why am I asking you for this change? Basically, because there is a VSCode extension called [Sourcery](https://sourcery.ai/) (which I think is awesome too) recommends [avoiding-builtin-shadow](https://docs.sourcery.ai/Reference/Python/Default-Rules/avoid-builtin-shadow/) when using `id` as variable name.

I also think this gives more flexibility to the awesome extension.

Thank you

**Comment by Pevtrick** [comment]
Hi @Tes3awy,

thank you for your interest in my package. I am glad that it is of help to other people.
The idea behind the `__id_attribute__` property was that you can easily modify it to match your own naming conventions.
Did you try to set the property in your class to "pk"?

```python
class MyModel(HashidMixin, db.Model):
    __id_attribute__ = "pk"
    __tablename__ = "my_model"
    pk = db.Column(db.Integer, primary_key=True)
    ...
```

**Comment by Tes3awy** [comment]
> Hi @Tes3awy,
> 
> 
> 
> thank you for your interest in my package. I am glad that it is of help to other people.
> 
> The idea behind the `__id_attribute__` property was that you can easily modify it to match your own naming conventions.
> 
> Did you try to set the property in your class to "pk"?
> 
> 
> 
> ```python
> 
> class MyModel(HashidMixin, db.Model):
> 
>     __id_attribute__ = "pk"
> 
>     __tablename__ = "my_model"
> 
>     pk = db.Column(db.Integer, primary_key=True)
> 
>     ...
> 
> ```


My bad. This didn't come to my mind at all.

Thanks again, brother 🙏🏻
